[meta]
name = "COTD Live Qualifying"
author = "KuebelChris"
category = "Race"
version = "1.0"
siteid = 238

[script]
dependencies = [ "NadeoServices" ]
imports = [ "Permissions.as", "Time.as", "Formatting.as" ]

